theme: jekyll-theme-hacker
title: Ella Jameson's Project Hub
description: Hello, and welcome to my project hub! This is under construction, but once completed, this will serve as a cental hub for all of my projects, and more detailed information about them.
